### PR TITLE
Factory contract and Token contract

### PR DESCRIPTION
**Pull request by wild-mouse**
- Implemented `TokenFactory` contract which create a creator token and manage
(Due to no implementation of vesting contract yet. Token distribution is currently not fully implemented.)
- Implemented `FanToken` contract which is created by Factory for each creators

### CODE REVIEW

**Comment by wild-mouse** [comment]
Discussion:
- Is it necessary emitting events for The Graph may be used in the future such as `NewCreator` or `NewToken`?

**Comment by toshiakitakase** [comment]
I think we need to have Events when creating, staking and withdrawing tokens.

**Comment by wild-mouse** [comment]
> I think we need to have Events when creating, staking and withdrawing tokens.

Are these events used on frontend to check transaction results?

**Comment by toshiakitakase** [comment]
This is for collecting data with TheGraph and others. I think we'll be utilizing that on the frontend eventually.

**Comment by toshiakitakase** [comment]
Code is LGTM ^^

**Comment by wild-mouse** [comment]
> This is for collecting data with TheGraph and others. I think we'll be utilizing that on the frontend eventually.

Ok I understand, I'm gonna add it on other PR 👍

**Pull request merged**
