### PR TITLE
Add pausing staking

### LINKED ISSUE #16: Add pausing staking feature into StakingPool contract
Refer to #12

### PR DESCRIPTION
**Pull request by wild-mouse**
- Add pausing staking functionality 
- Add creator list to Pool contract to restrict a function call 

Close #16

### CODE REVIEW

**Comment by toshiakitakase** [comment]
I think the tokens earned up to that point should be made available for withdrawal even when the staking is stopped, because it is expected that the staking may stop during someone staking.

Does this make the calculation more complicated?

**Comment by wild-mouse** [comment]
> I think the tokens earned up to that point should be made available for withdrawal even when the staking is stopped, because it is expected that the staking may stop during someone staking.

"withdrawal" means `claim()` (not `withdraw()` )?

**Comment by toshiakitakase** [comment]
`claim()` and also `earned ()`

**Comment by wild-mouse** [comment]
Ok

**Comment by wild-mouse** [comment]
Fixed comment. Currently earned formula does not include timestamp variable, so checking logic simply check staking amount too.

**Review by toshiakitakase — APPROVED** [review]

**Comment by toshiakitakase** [comment]
LGTM

**Pull request merged**
