### PR TITLE
Add redeem and stop staking function

### PR DESCRIPTION
**Pull request by toshiakitakase**
For creator
- Add redeem function
- Add stop and restart staking function

### CODE REVIEW

**Comment by wild-mouse** [comment]
An error occurs on starting app:
```
./src/components/pages/DashboardPage.jsx
Module not found: Can't resolve '../templates/Dashboard' in '/Users/noguchi_tsukasa/.ghq/github.com/TART-tokyo/fan-stock/frontend/packages/react-app/src/components/pages'
```

**Comment by toshiakitakase** [comment]
Fixed

**Comment by wild-mouse** [comment]
Changing staking status button is only displayed. How about showing current status above the button?

**Comment by toshiakitakase** [comment]
I added staking status.

**Review by wild-mouse — APPROVED** [review]
LGTM 🏃‍♂️

**Pull request merged**
